import {CityMap,surface,color,lowerBound,positionAt} from './map.js';
import {Scene} from './scene.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={vehicle:'3139',day:'2026-09-14',route:'6',start:0,end:0,time:0,mode:'3d',map:false,analysisId:null};
let catalog=[],trip=null,windowData=null,analysis=null,exact=null,playing=false,frameId=0,lastTick=0,loadVersion=0,frameVersion=0,saveTimer,rangeTimer,noticeTimer,placeTimer,placeToken=0,passes=[];
const rawCache=new Map();
let timelineZoom=false;
const time=(t,ms=false)=>new Date(t+10800000).toISOString().slice(11,ms?23:19);
const date=t=>new Date(t+10800000).toLocaleDateString('ru-RU',{timeZone:'UTC',day:'numeric',month:'long',year:'numeric'});
const inputDate=t=>new Date(t+10800000).toISOString().slice(0,23);
const parseDate=v=>Date.parse(v+'+03:00');
const n=(v,d=1)=>v==null?'—':Number(v).toLocaleString('ru-RU',{maximumFractionDigits:d});
const routeName=r=>r==='all'?'Все маршруты':r==='0'?'Маршрут не определён':'Маршрут '+r;
const handleName=h=>({driver:'Водитель',cpilot:'cpilot',undeterminable:'Не определено'})[h]||h||'Нет данных';
function notice(text){clearTimeout(noticeTimer);$('#notification').textContent=text;$('#notification').hidden=false;noticeTimer=setTimeout(()=>$('#notification').hidden=true,6500);}
async function api(path,params={},body){const r=await fetch('/api/'+path+(body?'':'?'+new URLSearchParams(params)),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});let d;try{d=await r.json();}catch{throw Error('Сервер недоступен или вернул неверный ответ.');}if(!r.ok)throw Error(d.error||'Не удалось выполнить запрос');return d;}
const safe=fn=>(...args)=>Promise.resolve().then(()=>fn(...args)).catch(e=>notice(e.message));
function element(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function options(select,values,chosen){select.replaceChildren();values.forEach(([value,label])=>select.add(new Option(label,value)));if(values.some(v=>v[0]===chosen))select.value=chosen;}
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('sirius-theme',theme);redraw();}
const scene=new Scene($('#scene'));
const map=new CityMap($('#city-map'),items=>{passes=items;options($('#map-pass'),items.map((p,i)=>[String(i),`${time(p.start)}${p.end>p.start?'–'+time(p.end):''} · ${n(p.record.speed)} км/ч`]),'0');$('#map-status').textContent=items.length>1?`Найдено ${items.length} проездов. Выберите нужное время.`:'Место выбрано. Можно начать интервал здесь или переместить только курсор.';$('#map-set-start').disabled=!items.length;$('#map-seek').disabled=!items.length;},notice);

async function boot(){const theme=localStorage.getItem('sirius-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');document.documentElement.dataset.theme=theme;$('#open-trip').disabled=true;const h=await api('health');$('#server-status').textContent='Сервер доступен';if(h.import.status!=='ready'){$('#import-state').hidden=false;$('#import-state').textContent=h.import.status==='error'?'Ошибка импорта: '+h.import.error:`Подготовка архива: ${h.import.current||0} из ${h.import.total||'…'} файлов. Каталог появится после индексации.`;setTimeout(()=>safe(boot)(),2500);return;}$('#import-state').hidden=true;const data=await api('catalog');catalog=data.entries;if(!catalog.length)throw Error('Каталог пока пуст');$('#archive-hours').textContent=n(data.coverage.total_hours??data.coverage.vehicles.reduce((s,r)=>s+r.combined_hours,0));const vehicles=[...new Set(catalog.map(r=>r.vehicle))];$('#catalog-summary').textContent=`${vehicles.length} вагонов · ${data.import.records.toLocaleString('ru-RU')} записей`;$('#archive-caption').textContent='14 сентября — 6 октября 2026 · с остановками';options($('#vehicle-select'),vehicles.map(v=>[v,'Вагон '+v]),state.vehicle);updateDates();$('#open-trip').disabled=false;await loadHistory();if(location.hash.startsWith('#work?')){const p=Object.fromEntries(new URLSearchParams(location.hash.slice(6)));await openTrip(p);} }
function updateDates(){const vehicle=$('#vehicle-select').value;const days=[...new Set(catalog.filter(r=>r.vehicle===vehicle).map(r=>r.day))];options($('#date-select'),days.map(d=>[d,date(Date.parse(d+'T12:00:00+03:00'))]),$('#date-select').value||state.day);updateRoutes();}
function updateRoutes(){const entries=catalog.filter(r=>r.vehicle===$('#vehicle-select').value&&r.day===$('#date-select').value);options($('#route-select'),[['all','Все маршруты за день'],...entries.map(r=>[r.route,routeName(r.route)+(r.n<5?' · единичные записи':'')])],$('#route-select').value||state.route);selectionDescription();}
function selectionDescription(){const entries=catalog.filter(r=>r.vehicle===$('#vehicle-select').value&&r.day===$('#date-select').value&&($('#route-select').value==='all'||r.route===$('#route-select').value));const hours=entries.reduce((s,r)=>s+r.hours,0),hasJson=entries.some(r=>r.json_n>0);$('#selection-description').textContent=`${n(hours)} ч наблюдений · ${hasJson?'подробные JSON + CSV':'только CSV'} · ${entries.length?time(Math.min(...entries.map(r=>r.start)))+'–'+time(Math.max(...entries.map(r=>r.end))):'нет данных'}`;}
async function loadHistory(){const data=await api('history');const list=$('#history-list');list.replaceChildren();if(!data.items.length){list.append(element('div','Открытые поездки и сохранённые разборы появятся здесь.','history-empty'));return;}for(const r of data.items){const b=element('button',undefined,'history-item');const title=element('div');title.append(element('strong',r.title),element('small',`${time(r.state.start)}–${time(r.state.end)} · курсор ${time(r.state.time)}`));b.append(title,element('span',r.kind==='analysis'?'Анализ':'Просмотр','badge '+(r.kind==='analysis'?'saved':'')),element('small',new Date(r.updated).toLocaleString('ru-RU')));b.onclick=safe(()=>openTrip(r.state));list.append(b);}}
function serialized(){return {...state,time:Math.round(state.time),start:Math.round(state.start),end:Math.round(state.end)};}
function urlState(){if(!trip)return;const p=new URLSearchParams(Object.entries(serialized()).filter(([,v])=>v!==null));history.replaceState(null,'','#work?'+p);}
function saveView(){clearTimeout(saveTimer);if(!trip||$('#work-view').hidden)return;saveTimer=setTimeout(()=>{urlState();api('history',{}, {state:serialized(),kind:'view'}).catch(e=>notice(e.message));},550);}
async function openTrip(input){stop();const token=++loadVersion;$('#open-trip').disabled=true;$('#server-status').textContent='Загружаем поездку…';try{const vehicle=String(input.vehicle),day=String(input.day),route=String(input.route||'all');if(!catalog.some(r=>r.vehicle===vehicle&&r.day===day&&(route==='all'||r.route===route)))throw Error('Такой комбинации вагона, даты и маршрута нет в архиве');const data=await api('trip',{vehicle,day,route});if(token!==loadVersion)return;trip=data;Object.assign(state,{vehicle,day,route,mode:input.mode==='2d'?'2d':'3d',map:input.map===true||input.map==='true',analysisId:input.analysisId||null});const first=trip.episodes.find(e=>e.type==='Brake')||trip.episodes[0];state.start=Number(input.start)||Math.max(trip.start,(first?.start||trip.start)-15000);state.end=Number(input.end)||Math.min(trip.end,state.start+120000);state.start=Math.max(trip.start,Math.min(trip.end,state.start));state.end=Math.max(state.start,Math.min(trip.end,state.end));state.time=Math.max(state.start,Math.min(state.end,Number(input.time)||first?.start||state.start));analysis=null;windowData=null;exact=null;$('#analysis-result').hidden=true;$('#home-view').hidden=true;$('#work-view').hidden=false;$('#trip-title').textContent=`Вагон ${vehicle} / ${routeName(route).toLowerCase()}`;$('#trip-caption').textContent=`${date(trip.start)} · ${time(trip.start)}–${time(trip.end)} · ${trip.gaps.length?trip.gaps.length+' разрывов записи':'непрерывное покрытие'}`;$('#source-badge').textContent=trip.series.some(r=>r.family==='json')?'JSON + CSV':'CSV';scene.setTrack(trip.track,vehicle);map.setTrack(trip.track);passes=[];$('#map-pass').replaceChildren();$('#map-set-start').disabled=true;$('#map-seek').disabled=true;options($('#snapshot-select'),[['','Выберите снимок'],...trip.snapshots.map(r=>[String(r.id),time(r.t,true)])],'');$('#go-snapshot').disabled=!trip.snapshots.length;scene.snapshot=null;$('#snapshot-content').textContent=trip.snapshots.length?`Доступно ${trip.snapshots.length} расширенных снимков. Выберите время для просмотра.`:'В этой записи нет расширенных снимков объектов. Геометрия препятствия неизвестна.';scene.showSnapshot=false;$('#show-snapshot').checked=false;renderRange();renderMode();await loadWindow();if(state.analysisId){try{analysis=await api('analysis',{id:state.analysisId});renderAnalysis();}catch(e){state.analysisId=null;notice(e.message);}}saveView();window.scrollTo({top:0,behavior:'instant'});}finally{$('#open-trip').disabled=false;$('#server-status').textContent='Сервер доступен';}}
function renderRange(){if(!trip)return;$('#range-start').value=inputDate(state.start);$('#range-end').value=inputDate(state.end);$('#start-output').textContent=time(state.start);$('#end-output').textContent=time(state.end);for(const key of ['start','end']){const el=$('#'+key+'-slider');el.min=trip.start;el.max=trip.end;el.value=state[key];}$('#cursor-slider').min=state.start;$('#cursor-slider').max=state.end;$('#cursor-slider').value=state.time;analysisStatus();drawOverview();map.update(state.time,state.start,state.end,currentRow());}
function analysisStatus(){if(!analysis){$('#analysis-state').textContent='Выберите интервал и запустите анализ.';$('#analysis-state').classList.remove('error');return;}const stale=analysis.start!==state.start||analysis.end!==state.end;$('#analysis-state').textContent=(stale?'Для предыдущего интервала. ':'Сохранено · ')+time(analysis.start)+'–'+time(analysis.end)+(stale?' Выполните новый анализ.':' · правила '+analysis.rules_version);$('#analysis-state').classList.toggle('error',stale);}
async function loadWindow(){const token=++frameVersion;$('#scene-caption').textContent='Загружаем выбранный интервал…';const d=await api('window',state);if(token!==frameVersion)return;windowData=d;exact=null;renderCurrent();await fetchFrame();saveView();}
async function applyRange(start,end){stop();if(!Number.isFinite(start)||!Number.isFinite(end)||end<start)throw Error('Начало должно быть раньше конца. Укажите корректное время.');state.start=Math.max(trip.start,Math.min(trip.end,start));state.end=Math.max(state.start,Math.min(trip.end,end));state.time=Math.max(state.start,Math.min(state.end,state.time));renderRange();await loadWindow();}
function currentRow(){if(exact&&exact.time===Math.round(state.time))return exact.record;const rows=windowData?.rows||[];let i=lowerBound(rows,state.time+1)-1;return rows[i]||(windowData?.context&&windowData.context.t<=state.time?windowData.context:null);}
async function fetchFrame(){const t=Math.round(state.time),vehicle=state.vehicle,route=state.route;const r=await api('frame',{vehicle,route,t});if(t!==Math.round(state.time)||vehicle!==state.vehicle)return;exact={time:t,record:r.record};renderCurrent();schedulePlace();if($('#raw-details').open&&r.record)await showRaw(r.record.id);}
function schedulePlace(){clearTimeout(placeTimer);const p=positionAt(trip.track,state.time,currentRow());if(!p){$('#scene-location').textContent='Нет надёжной позиции';return;}const token=++placeToken;placeTimer=setTimeout(async()=>{try{const g=await api('place',{lat:p.lat,lon:p.lon});if(token!==placeToken)return;$('#scene-location').textContent=g.street?.name?g.street.name+(g.street.distance>30?' · рядом с улицей':''):'Название улицы не найдено';}catch{$('#scene-location').textContent='Название улицы недоступно';}},180);}
function renderCurrent(){if(!trip)return;const r=currentRow(),age=r?state.time-r.t:Infinity,gap=age>30000||!r;$('#cursor-time').textContent=time(state.time,true);$('#cursor-slider').value=state.time;const position=positionAt(trip.track,state.time,currentRow());$('#scene-gap').hidden=!!position&&!gap;$('#scene-gap').textContent=gap?'Нет наблюдений в выбранный момент':'Нет надёжных координат для реконструкции';scene.time=state.time;scene.current=r;scene.draw();if(state.map)map.update(state.time,state.start,state.end,currentRow());$('#current-speed').textContent=!gap&&r.speed!=null?(r.flags.includes('speed_out_of_range')?'Нужна проверка':n(r.speed)+' км/ч'):'—';$('#current-handle').textContent=gap?'Нет данных':handleName(r.handle);const acts=[];if(!gap)for(const [k,label] of [['act_danger','Препятствие'],['act_light','Светофор'],['act_speed','Скорость']]){if(r[k]==='ActuationAct')acts.push(label+': вмешательство');else if(r[k]==='WarningAct')acts.push(label+': предупреждение');else if(r[k]&&r[k].startsWith('CSV:')&&!['CSV:0','CSV:'].includes(r[k]))acts.push(label+': код '+r[k].slice(4));}$('#current-action').textContent=gap?'Нет данных':acts.join(' · ')||'Без активного запроса';const brakes=[];if(!gap)for(const [bit,label] of [[1,'Механический'],[2,'Рельсовый'],[4,'Экстренный'],[8,'Аварийный']])if(r.brakes&bit)brakes.push(label);$('#current-brake').textContent=gap?'Нет данных':brakes.join(', ')||'Нет сигнала';
    const notes=[];if(gap)notes.push('Дискретные сигналы устарели или отсутствуют.');else{notes.push(`${r.family==='json'?'JSON':'CSV'} · запись ${time(r.t,true)}${age>1000?' · возраст '+n(age/1000)+' с':''}.`);if(r.flags.includes('position_disagreement'))notes.push('Расчётная позиция расходится с GPS; показан исходный GPS.');if(r.flags.includes('speed_out_of_range'))notes.push('Аномальная скорость в источнике: '+n(r.speed)+' км/ч.');if(r.flags.includes('localization_not_converged'))notes.push('Локализация не сошлась.');}if(windowData?.sampled)notes.push('Обзорная выборка; при паузе загружается точная запись.');$('#quality-note').textContent=notes.join(' ');$('#quality-note').classList.toggle('warning',gap||r?.flags.includes('position_disagreement'));$('#scene-caption').textContent=position?'Типовая модель · '+(position.method==='odometry'?'GPS + одометрия сегмента':'путь по GPS')+(position.interpolated?' · интерполяция':''):'Позиция неизвестна';$('#odometry-note').textContent=r?`Позиция на сегменте: ${r.pos??'нет данных'}; сегмент: ${r.segment??'не указан'}. Значения разных сегментов не суммируются.`:'';drawOverview();}
async function seek(t,{pause=true,exactRecord=null}={}){if(pause)stop();state.time=Math.max(state.start,Math.min(state.end,Math.round(t)));exact=exactRecord?{time:state.time,record:exactRecord}:null;renderCurrent();if(pause){await fetchFrame();saveView();}}
function renderMode(){scene.mode=state.mode;scene.angle=+$('#camera-angle').value;scene.zoom=+$('#scene-zoom').value;$('#view-2d').setAttribute('aria-pressed',state.mode==='2d');$('#view-3d').setAttribute('aria-pressed',state.mode==='3d');$('#camera-label').hidden=state.mode==='2d';$('#map-panel').hidden=!state.map;$('#workspace-layout').classList.toggle('map-open',state.map);$('#map-toggle').setAttribute('aria-expanded',state.map);scene.draw();if(state.map){map.load();map.draw();}}
function drawOverview(){
 if(!trip)return;const frame=surface($('#overview'));if(!frame)return;
 const {ctx,w}=frame,L=35,R=w-12,T=18,B=85;
 const from=timelineZoom?state.start:trip.start,to=timelineZoom?state.end:trip.end;
 const duration=Math.max(1,to-from),series=(timelineZoom?windowData?.rows||[]:trip.series);
 const valid=series.filter(r=>r.speed!=null&&!r.flags.includes('speed_out_of_range'));
 const vmax=Math.max(30,...valid.map(r=>r.speed)),x=t=>L+(t-from)/duration*(R-L),y=v=>B-Math.min(vmax,Math.max(0,v))/vmax*(B-T);
 ctx.fillStyle=color('--soft');ctx.fillRect(Math.max(L,x(state.start)),T,Math.max(2,Math.min(R,x(state.end))-Math.max(L,x(state.start))),B-T);
 ctx.font='11px Segoe UI';ctx.fillStyle=color('--muted');ctx.fillText('км/ч',3,11);
 for(const v of [0,Math.round(vmax/2),Math.ceil(vmax)]){ctx.strokeStyle=color('--grid');ctx.beginPath();ctx.moveTo(L,y(v));ctx.lineTo(R,y(v));ctx.stroke();ctx.fillText(String(v),3,y(v)+4);}
 const intervalGaps=timelineZoom?windowData?.gaps||[]:trip.gaps;
 for(const [a,b] of intervalGaps){if(b<from||a>to)continue;ctx.fillStyle=color('--border');ctx.globalAlpha=.55;ctx.fillRect(Math.max(L,x(a)),T,Math.min(R,x(b))-Math.max(L,x(a)),B-T);ctx.globalAlpha=1;}
 ctx.strokeStyle=color('--accent');ctx.lineWidth=1.5;ctx.beginPath();let prev=null;
 for(const r of series){if(r.t<from||r.t>to)continue;if(r.speed==null||r.flags.includes('speed_out_of_range')){prev=null;continue;}if(!prev||intervalGaps.some(([a,b])=>prev.t<=a&&r.t>=b))ctx.moveTo(x(r.t),y(r.speed));else ctx.lineTo(x(r.t),y(r.speed));prev=r;}ctx.stroke();
 const bins=new Set();for(const e of trip.episodes){if(e.end<from||e.start>to)continue;const px=Math.round(x(Math.max(from,e.start))/4)*4,yy={Warn:14,Brake:24,OverSpeed:34}[e.type]||14,key=px+e.type;if(bins.has(key))continue;bins.add(key);ctx.fillStyle=color(e.type==='Brake'?'--brake':e.type==='Warn'?'--warn':'--purple');ctx.beginPath();ctx.arc(px,yy,2.5,0,Math.PI*2);ctx.fill();}
 ctx.strokeStyle=color('--text');ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x(state.time),T);ctx.lineTo(x(state.time),B+3);ctx.stroke();
 for(let i=0;i<4;i++){const t=from+duration*i/3;ctx.textAlign=i===0?'left':i===3?'right':'center';ctx.fillStyle=color('--muted');ctx.fillText(time(t),x(t),110);}ctx.textAlign='left';
 const outliers=series.filter(r=>r.flags.includes('speed_out_of_range'));if(outliers.length){ctx.fillStyle=color('--brake');ctx.fillText('× Аномальные скорости: '+outliers.length+' (см. исходные записи)',L,128);for(const r of outliers){ctx.fillText('×',x(r.t)-3,T+7);}}
}
function redraw(){drawOverview();scene.draw();map.draw();}
async function showRaw(id){let d=rawCache.get(id);if(!d){d=await api('record',{id});rawCache.set(id,d);}$('#raw-record').textContent=JSON.stringify(d.raw,null,2);$('#record-reference').textContent=`${d.source.path} · ${d.record.family==='json'?'блок':'строка'} ${d.sequence_index}${d.json_pointer?' · '+d.json_pointer:''} · SHA-256 записи ${d.record_hash}`;return d;}
async function evidence(id){const d=await showRaw(id);if(d.record.t<state.start||d.record.t>state.end){await applyRange(Math.max(trip.start,d.record.t-15000),Math.min(trip.end,d.record.t+30000));}await seek(d.record.t,{exactRecord:d.record});exact={time:d.record.t,record:d.record};renderCurrent();$('#raw-details').open=true;saveView();}
function evidenceButton(id,text){const b=element('button',text||'Запись #'+id,'evidence-link');b.type='button';b.dataset.evidenceId=id;b.onclick=safe(()=>evidence(id));return b;}
function renderAnalysis(){if(!analysis)return;$('#analysis-result').hidden=false;$('#analysis-summary').textContent=analysis.summary;analysisStatus();const cards=$('#evidence-cards');cards.replaceChildren();const priority=['intervention','brake','control','warning','speed','target'];const chosen=[...analysis.facts].sort((a,b)=>priority.indexOf(a.kind)-priority.indexOf(b.kind)).slice(0,3).sort((a,b)=>a.t-b.t);for(const f of chosen){const b=element('button',undefined,'evidence-card');b.type='button';b.dataset.evidenceId=f.evidence_ids[0];b.append(element('span',time(f.t,true),'time'),element('strong',f.title),element('p',f.text));b.onclick=safe(()=>evidence(f.evidence_ids[0]));cards.append(b);}const all=$('#all-facts');all.replaceChildren();for(const f of [...analysis.facts].sort((a,b)=>a.t-b.t)){const row=element('div',undefined,'fact-row'),body=element('div');body.append(element('h3',f.title),element('p',f.text));for(const id of f.evidence_ids)body.append(evidenceButton(id));row.append(element('span',time(f.t,true),'small tabular'),body);all.append(row);}$('#analysis-limits').replaceChildren(...analysis.limitations.map(t=>element('li',t)));$('#answer').replaceChildren();}
async function doAnalyze(){const button=$('#analyze-button');button.disabled=true;button.textContent='Анализируем…';const request={vehicle:state.vehicle,route:state.route,start:state.start,end:state.end};try{const result=await api('analyze',{},request);if(result.vehicle!==state.vehicle||result.route!==state.route)return;analysis=result;state.analysisId=result.id;renderAnalysis();urlState();await api('history',{}, {id:'analysis:'+result.id,kind:'analysis',state:{...serialized(),start:result.start,end:result.end,time:result.start,analysisId:result.id}});notice('Анализ сохранён. Каждое утверждение можно проверить по исходной записи.');}finally{button.disabled=false;button.textContent='Анализировать интервал';}}
async function ask(question){if(!analysis)throw Error('Сначала выполните анализ выбранного интервала');if(analysis.start!==state.start||analysis.end!==state.end)throw Error('Интервал изменился. Выполните новый анализ перед вопросом.');$('#answer').textContent='Проверяем записи…';const a=await api('question',{}, {analysis_id:analysis.id,question});$('#answer').replaceChildren(element('p',a.text));for(const id of a.evidence_ids)$('#answer').append(evidenceButton(id));}
async function selectSnapshot(){const id=+$('#snapshot-select').value;if(!id){scene.snapshot=null;return;}const d=await api('record',{id});rawCache.set(id,d);const tel=d.raw.telemetry_data;const stamp=Date.parse(d.raw.telemetry_timestamp)||d.record.t;scene.snapshot={data:tel,t:stamp};const container=$('#snapshot-content');container.replaceChildren(element('p',`Снимок ${time(stamp,true)} · событие ${time(d.record.t,true)} · ${tel.subsystem}`));const objects=tel.object?[tel.object]:(tel.trafficLights||[]);const table=element('table',undefined,'snapshot-table');const head=element('tr');for(const text of ['Тип / состояние','x / y','Сигнал'])head.append(element('th',text));table.append(head);objects.slice(0,30).forEach(o=>{const row=element('tr');row.append(element('td',`${o.type} · ${o.state}`),element('td',`${n(o.pose?.x)} / ${n(o.pose?.y)}`),element('td',o.tlSignal||'—'));table.append(row);});container.append(table,element('p','Оси и единицы локальных координат не подтверждены. На схеме условно x — поперёк, y — вперёд. Потерянные и прогнозируемые объекты не считаются наблюдаемыми.','small'));scene.draw();}
function stop(){playing=false;cancelAnimationFrame(frameId);$('#play').textContent='▶ Воспроизвести';}
function play(){if(playing){stop();safe(fetchFrame)();saveView();return;}if(!windowData?.rows.length){notice('В выбранном интервале нет записей.');return;}if(state.time>=state.end)state.time=state.start;playing=true;lastTick=performance.now();$('#play').textContent='Ⅱ Пауза';let lastRender=0;function tick(now){if(!playing)return;const previous=state.time;state.time=Math.min(state.end,state.time+(now-lastTick)*+$('#play-speed').value);lastTick=now;const gap=windowData.gaps.find(([a,b])=>previous<=a&&state.time>a&&b>state.time);if(gap){state.time=gap[0];stop();notice('Достигнут разрыв записи. Выберите следующий наблюдаемый момент.');safe(fetchFrame)();saveView();return;}exact=null;if(now-lastRender>32){renderCurrent();lastRender=now;}if(state.time>=state.end){stop();safe(fetchFrame)();saveView();return;}frameId=requestAnimationFrame(tick);}frameId=requestAnimationFrame(tick);}
function step(direction){const rows=windowData?.rows||[];if(!rows.length)return;let i=lowerBound(rows,state.time);if(direction<0)i=Math.max(0,i-1);else i=Math.min(rows.length-1,i+(rows[i]?.t<=state.time?1:0));return seek(rows[i].t);}
async function nextEvent(direction){const eps=trip.episodes;const e=direction>0?eps.find(e=>e.start>state.time+1):eps.findLast(e=>e.start<state.time-1);if(!e){notice('Других событий в этом направлении нет.');return;}await applyRange(Math.max(trip.start,e.start-15000),Math.min(trip.end,Math.max(e.end+15000,e.start+30000)));await seek(e.start);}

$('#vehicle-select').onchange=updateDates;$('#date-select').onchange=updateRoutes;$('#route-select').onchange=selectionDescription;
$('#selection-form').onsubmit=e=>{e.preventDefault();safe(()=>openTrip({vehicle:$('#vehicle-select').value,day:$('#date-select').value,route:$('#route-select').value}))();};
async function home(){stop();clearTimeout(saveTimer);if(trip)await api('history',{}, {state:serialized(),kind:'view'});$('#work-view').hidden=true;$('#home-view').hidden=false;history.replaceState(null,'','#home');await loadHistory();window.scrollTo({top:0,behavior:'instant'});}
$('#back-home').onclick=safe(home);$('.brand').onclick=e=>{e.preventDefault();safe(home)();};
$('#timeline-zoom').onclick=()=>{timelineZoom=!timelineZoom;$('#timeline-zoom').textContent=timelineZoom?'Вся поездка':'Приблизить интервал';drawOverview();};
$('#apply-range').onclick=safe(()=>applyRange(parseDate($('#range-start').value),parseDate($('#range-end').value)));
for(const key of ['start','end']){$('#'+key+'-slider').oninput=e=>{stop();state[key]=+e.target.value;if(state.start>state.end)state[key==='start'?'end':'start']=state[key];state.time=Math.max(state.start,Math.min(state.end,state.time));renderRange();clearTimeout(rangeTimer);rangeTimer=setTimeout(()=>safe(loadWindow)(),250);};}
$$('[data-span]').forEach(b=>b.onclick=safe(()=>applyRange(Math.max(trip.start,state.time-+b.dataset.span*.25),Math.min(trip.end,state.time+ +b.dataset.span*.75))));$('#whole-trip').onclick=safe(()=>applyRange(trip.start,trip.end));
$('#cursor-slider').oninput=e=>{stop();state.time=+e.target.value;exact=null;renderCurrent();};$('#cursor-slider').onchange=safe(async()=>{await fetchFrame();saveView();});
$('#overview').onclick=safe(async e=>{const w=e.currentTarget.clientWidth,t=(timelineZoom?state.start:trip.start)+(e.offsetX-35)/Math.max(1,w-47)*Math.max(1,(timelineZoom?state.end-state.start:trip.end-trip.start));const closest=trip.episodes.reduce((best,r)=>!best||Math.abs(r.start-t)<Math.abs(best.start-t)?r:best,null);if(e.offsetY<42&&closest){await applyRange(Math.max(trip.start,closest.start-15000),Math.min(trip.end,closest.end+30000));await seek(closest.start);}else if(t<state.start||t>state.end){const span=Math.min(120000,state.end-state.start||120000);await applyRange(Math.max(trip.start,t-span/4),Math.min(trip.end,t+span*.75));await seek(t);}else await seek(t);});
$('#play').onclick=play;$('#step-back').onclick=safe(()=>step(-1));$('#step-forward').onclick=safe(()=>step(1));$('#previous-event').onclick=safe(()=>nextEvent(-1));$('#next-event').onclick=safe(()=>nextEvent(1));
for(const mode of ['2d','3d'])$('#view-'+mode).onclick=()=>{state.mode=mode;renderMode();saveView();};
$('#camera-angle').oninput=renderMode;$('#scene-zoom').oninput=renderMode;$('#reset-camera').onclick=()=>{$('#camera-angle').value=220;$('#scene-zoom').value=1.25;renderMode();};
function toggleMap(value){state.map=value;renderMode();saveView();}$('#map-toggle').onclick=()=>toggleMap(!state.map);$('#map-close').onclick=()=>toggleMap(false);$('#map-plus').onclick=()=>map.zoom(1.5);$('#map-minus').onclick=()=>map.zoom(1/1.5);$('#map-fit').onclick=()=>map.fit();
$('#map-set-start').onclick=safe(async()=>{const p=passes[+$('#map-pass').value];if(!p)return;const span=state.end-state.start,start=p.record.t;await applyRange(start,Math.min(trip.end,start+span));await seek(start);notice(start+span>trip.end?'Конец интервала ограничен концом записи.':'Начало интервала выбрано на карте.');});
$('#map-seek').onclick=safe(async()=>{const p=passes[+$('#map-pass').value];if(!p)return;if(p.record.t<state.start||p.record.t>state.end){notice('Момент находится вне выбранного интервала. Используйте «Начать интервал здесь».');return;}await seek(p.record.t);});
$('#analyze-button').onclick=safe(doAnalyze);$$('[data-question]').forEach(b=>b.onclick=safe(()=>ask(b.dataset.question)));$('#question-form').onsubmit=e=>{e.preventDefault();safe(()=>ask($('#question-input').value))();};
$('#raw-details').ontoggle=()=>{if($('#raw-details').open&&currentRow())safe(()=>showRaw(currentRow().id))();};$('#snapshot-select').onchange=safe(selectSnapshot);$('#go-snapshot').onclick=safe(async()=>{const id=+$('#snapshot-select').value;if(!id){notice('Сначала выберите снимок.');return;}await selectSnapshot();await evidence(id);const stamp=scene.snapshot.t;if(stamp<state.start||stamp>state.end)await applyRange(Math.max(trip.start,stamp-15000),Math.min(trip.end,stamp+15000));await seek(stamp);});$('#show-snapshot').onchange=e=>{scene.showSnapshot=e.target.checked;scene.draw();};
$('#export-analysis').onclick=()=>{if(!analysis)return;const file=new Blob([JSON.stringify(analysis,null,2)],{type:'application/json'}),a=element('a');a.href=URL.createObjectURL(file);a.download=`sirius-${analysis.vehicle}-${analysis.id.slice(0,8)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('#theme-button').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');new ResizeObserver(redraw).observe(document.querySelector('main'));
document.addEventListener('keydown',e=>{if($('#work-view').hidden||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();play();}if(e.code==='ArrowRight'){e.preventDefault();safe(()=>step(1))();}if(e.code==='ArrowLeft'){e.preventDefault();safe(()=>step(-1))();}});
safe(boot)();
