export const color=name=>getComputedStyle(document.documentElement).getPropertyValue(name).trim();
export function surface(canvas){const w=canvas.clientWidth,h=canvas.clientHeight,d=Math.min(devicePixelRatio||1,2);if(!w||!h)return null;if(canvas.width!==Math.round(w*d)||canvas.height!==Math.round(h*d)){canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);}const ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);return {ctx,w,h};}
export function lowerBound(rows,t){let a=0,b=rows.length;while(a<b){let m=(a+b)>>1;if(rows[m].t<t)a=m+1;else b=m;}return a;}
export function positionAt(track,t,odometry=null){if(!track.length||t<track[0].t)return null;let i=lowerBound(track,t);if(i<track.length&&track[i].t===t&&track[i].lat&&track[i].lon)return {...track[i],interpolated:false,method:'gps'};const a=track[Math.max(0,i-1)],b=track[Math.min(i,track.length-1)];if(!a?.lat||!b?.lat||!a.lon||!b.lon||t-a.t>30000||b.t-a.t>30000)return null;const dist=Math.hypot((a.lat-b.lat)*111320,(a.lon-b.lon)*55660),dt=(b.t-a.t)/1000;if(dt>0&&dist/dt>40)return null;let f=b.t===a.t?0:Math.max(0,Math.min(1,(t-a.t)/(b.t-a.t))),method='gps';if(odometry&&a.segment&&a.segment===b.segment&&a.segment===odometry.segment&&a.pos!=null&&b.pos!=null&&odometry.pos!=null&&b.pos>a.pos&&b.pos-a.pos<300&&odometry.pos>=a.pos&&odometry.pos<=b.pos&&odometry.t>=a.t&&odometry.t<=t&&t-odometry.t<=1000){f=(odometry.pos-a.pos)/(b.pos-a.pos);method='odometry';}return {...a,lat:a.lat+(b.lat-a.lat)*f,lon:a.lon+(b.lon-a.lon)*f,interpolated:f>0&&f<1,method};}

export class CityMap{
  constructor(canvas,onPick,onError){this.canvas=canvas;this.onPick=onPick;this.onError=onError;this.center=[30.32,59.96];this.scale=0.08;this.features=[];this.track=[];this.time=0;this.start=0;this.end=0;this.request=0;this.ready=false;let drag=null;
    canvas.addEventListener('pointerdown',e=>{drag={x:e.offsetX,y:e.offsetY,center:[...this.center],moved:false};canvas.setPointerCapture(e.pointerId);});
    canvas.addEventListener('pointermove',e=>{if(!drag)return;let dx=e.offsetX-drag.x,dy=e.offsetY-drag.y;if(Math.hypot(dx,dy)>5)drag.moved=true;this.center=[drag.center[0]-dx/this.scale/55660,drag.center[1]+dy/this.scale/111320];this.draw();});
    canvas.addEventListener('pointerup',e=>{if(!drag)return;if(!drag.moved)this.pick(e.offsetX,e.offsetY);else this.load();drag=null;});canvas.addEventListener('pointercancel',()=>drag=null);
    canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom(e.deltaY<0?1.25:0.8);},{passive:false});
    new ResizeObserver(()=>{if(this.ready)this.load();this.draw();}).observe(canvas);
  }
  project(lon,lat){return [this.canvas.clientWidth/2+(lon-this.center[0])*55660*this.scale,this.canvas.clientHeight/2-(lat-this.center[1])*111320*this.scale];}
  setTrack(track){this.track=track;this.fit();}
  fit(){const ps=this.track.filter(r=>r.lat>59.4&&r.lat<60.5&&r.lon>29&&r.lon<31.5);if(!ps.length)return;const lons=ps.map(p=>p.lon),lats=ps.map(p=>p.lat);const lo=Math.min(...lons),hi=Math.max(...lons),la=Math.min(...lats),ha=Math.max(...lats);this.center=[(lo+hi)/2,(la+ha)/2];this.scale=Math.min(Math.max(this.canvas.clientWidth,320)/Math.max(300,(hi-lo)*55660),Math.max(this.canvas.clientHeight,390)/Math.max(300,(ha-la)*111320))*.78;this.ready=true;this.load();}
  zoom(f){this.scale=Math.max(.009,Math.min(7,this.scale*f));this.load();}
  focus(p){if(!p)return;this.center=[p.lon,p.lat];this.scale=Math.max(this.scale,.6);this.load();}
  async load(){if(!this.canvas.clientWidth)return;const id=++this.request,w=this.canvas.clientWidth/this.scale/55660/2,h=this.canvas.clientHeight/this.scale/111320/2;try{const bounds=[this.center[0]-w,this.center[1]-h,this.center[0]+w,this.center[1]+h];const r=await fetch('/api/map?'+new URLSearchParams({bounds:bounds.join(',')}));const d=await r.json();if(!r.ok)throw Error(d.error);if(id!==this.request)return;this.features=d.features;this.draw();}catch(e){this.onError(e.message);}}
  update(time,start,end,record=null){this.time=time;this.start=start;this.end=end;this.current=record;this.draw();}
  pick(x,y){let nearest=null,best=Infinity;for(const r of this.track){if(!r.lat||!r.lon)continue;const p=this.project(r.lon,r.lat),d=Math.hypot(p[0]-x,p[1]-y);if(d<best){best=d;nearest=r;}}if(!nearest||best>28){this.onError('Выберите точку на линии записанного трека.');return;}
    const near=this.track.filter(r=>r.lat&&r.lon&&Math.hypot((r.lat-nearest.lat)*111320,(r.lon-nearest.lon)*55660)<Math.max(12,8/this.scale));const passes=[];let group=[];for(const r of near){if(group.length&&r.t-group.at(-1).t>60000){passes.push(group);group=[];}group.push(r);}if(group.length)passes.push(group);this.onPick(passes.map(g=>({start:g[0].t,end:g.at(-1).t,record:g.reduce((a,r)=>Math.hypot(r.lat-nearest.lat,(r.lon-nearest.lon)*.5)<Math.hypot(a.lat-nearest.lat,(a.lon-nearest.lon)*.5)?r:a)})));}
  draw(){const s=surface(this.canvas);if(!s)return;const {ctx,w,h}=s;ctx.fillStyle=color('--bg');ctx.fillRect(0,0,w,h);const drawLine=(ps,stroke,width)=>{ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.beginPath();ps.forEach((p,i)=>{const a=this.project(...p);i?ctx.lineTo(...a):ctx.moveTo(...a);});ctx.stroke();};
    for(const f of this.features)if(f.kind==='street')drawLine(f.points,color('--map-road'),this.scale>.5?8:2);
    for(const f of this.features)if(f.kind==='rail')drawLine(f.points,color('--muted'),1);
    let prev=null;for(const r of this.track){if(!r.lat||!r.lon){prev=null;continue;}if(prev){const dt=r.t-prev.t,dist=Math.hypot((r.lat-prev.lat)*111320,(r.lon-prev.lon)*55660);if(dt>0&&dt<=30000&&dist/(dt/1000)<40)drawLine([[prev.lon,prev.lat],[r.lon,r.lat]],r.t>=this.start&&r.t<=this.end?color('--accent'):color('--border'),r.t>=this.start&&r.t<=this.end?3:2);}prev=r;}
    if(this.scale>.2){const used=new Set(),boxes=[];ctx.font='11px Segoe UI';for(const f of this.features){if(!f.name||used.has(f.name))continue;const mid=f.points[Math.floor(f.points.length/2)],p=this.project(...mid),width=ctx.measureText(f.name).width;if(p[0]<15||p[0]+width>w-10||p[1]<30||p[1]>h-30||boxes.some(b=>Math.abs(b[1]-p[1])<22&&Math.abs(b[0]-p[0])<Math.max(width,b[2])))continue;ctx.fillStyle=color('--panel');ctx.fillRect(p[0]-3,p[1]-11,width+6,15);ctx.fillStyle=color('--muted');ctx.fillText(f.name,...p);boxes.push([...p,width]);used.add(f.name);}}
    const current=positionAt(this.track,this.time,this.current);if(current){const p=this.project(current.lon,current.lat);ctx.beginPath();ctx.arc(...p,7,0,Math.PI*2);ctx.fillStyle=color('--panel');ctx.fill();ctx.lineWidth=3;ctx.strokeStyle=color('--accent');ctx.stroke();}
    ctx.font='11px Segoe UI';ctx.fillStyle=color('--muted');ctx.fillText('Север ↑',12,20);const meters=this.scale>1?25:this.scale>.2?100:this.scale>.04?500:1000;ctx.strokeStyle=color('--text');ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(12,h-24);ctx.lineTo(12+meters*this.scale,h-24);ctx.stroke();ctx.fillText(meters>=1000?meters/1000+' км':meters+' м',12,h-8);
  }
}
